package com.hlz.gourdmall.mapper;

import com.hlz.gourdmall.model.CheckCode;
import com.hlz.gourdmall.model.CheckCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    long countByExample(CheckCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int deleteByExample(CheckCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int insert(CheckCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int insertSelective(CheckCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    List<CheckCode> selectByExample(CheckCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    CheckCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CheckCode record, @Param("example") CheckCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int updateByExample(@Param("record") CheckCode record, @Param("example") CheckCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int updateByPrimaryKeySelective(CheckCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Mon Dec 02 08:53:45 CST 2019
     */
    int updateByPrimaryKey(CheckCode record);
}