package com.hlz.gourdmall.model;

import java.util.Date;

public class CheckCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code.id
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code.uid
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code.create_time
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code.code
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_code.state
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code.id
     *
     * @return the value of check_code.id
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code.id
     *
     * @param id the value for check_code.id
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code.uid
     *
     * @return the value of check_code.uid
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code.uid
     *
     * @param uid the value for check_code.uid
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code.create_time
     *
     * @return the value of check_code.create_time
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code.create_time
     *
     * @param createTime the value for check_code.create_time
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code.code
     *
     * @return the value of check_code.code
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code.code
     *
     * @param code the value for check_code.code
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_code.state
     *
     * @return the value of check_code.state
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_code.state
     *
     * @param state the value for check_code.state
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_code
     *
     * @mbg.generated Sat Nov 23 14:41:16 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", createTime=").append(createTime);
        sb.append(", code=").append(code);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}