package com.hlz.gourdmall.model;

import java.util.Date;

public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.id
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.create_time
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.uid
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.id
     *
     * @return the value of token.id
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.id
     *
     * @param id the value for token.id
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token
     *
     * @return the value of token.token
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token
     *
     * @param token the value for token.token
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.create_time
     *
     * @return the value of token.create_time
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.create_time
     *
     * @param createTime the value for token.create_time
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.uid
     *
     * @return the value of token.uid
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.uid
     *
     * @param uid the value for token.uid
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Dec 03 11:10:57 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", token=").append(token);
        sb.append(", createTime=").append(createTime);
        sb.append(", uid=").append(uid);
        sb.append("]");
        return sb.toString();
    }
}